# Generated by Django 4.0.4 on 2022-05-12 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UploadedTime', models.DateTimeField(auto_created=True)),
                ('songname', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('file', models.FileField(upload_to='song', validators=[django.core.validators.FileExtensionValidator(['mp3'])])),
            ],
        ),
    ]
