# Generated by Django 4.0.4 on 2022-05-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='UploadedTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.PositiveBigIntegerField(),
        ),
    ]
